### ISSUE TITLE
Unable to build with Xcode 12.5 beta

### ISSUE THREAD

**Issue by jsorge** [skelpo/JSON#6]
I'm not sure if this project is maintained anymore (and I'm gonna take a crack at fixing it myself) but wanted to flag that this package doesn't work in Xcode 12.5 & Swift 5.4. There's a circular reference type error being thrown now (see the image below).

![Screen Shot 2021-02-17 at 1 50 03 PM](https://user-images.githubusercontent.com/2585841/108273407-6316c800-7128-11eb-88b8-b44302afe72f.png)

If you've got any quick ideas on how to fix it before I fling myself at it I'm all ears :)

Thanks!

**Comment by jsorge** [comment]
Thank you!!

**Comment by jsorge** [comment]
@proggeramlug It looks like the new tagged release is 1.0.1, but it should have been 1.1.3?
![Screen Shot 2021-02-19 at 9 59 17 AM](https://user-images.githubusercontent.com/2585841/108542863-228a8c00-7299-11eb-8f6a-1d3a5dafe5ba.png)

**Comment by proggeramlug** [comment]
@jsorge Fixed it!

**Comment by jsorge** [comment]
🎉
